[tool.codeflash]
# All paths are relative to this pyproject.toml's directory.
module-root = "."
tests-root = "tests"
test-framework = "pytest"
benchmarks-root = ""
ignore-paths = []
disable-telemetry = true
formatter-cmds = ["disabled"]
